language: bash

go:
    - "1.9"

env:
    global:
        - SSH_KEY="id_rsa"
        - GIT_NAME="Lutz Behnke"
        - GIT_EMAIL="Lutz Behnke@gmx.de"
        - SOURCE_DIR="public"
        - DEPLOY_BRANCH="source"
        - HUGO_VERSION="0.36.1"
        - HUGO_UGLYURLS="true"

before_install:
    - echo openssl aes-256-cbc -K $encrypted_5badef0aa7c9_key -iv $encrypted_5badef0aa7c9_iv -in id_rsa.enc -out id_rsa -d

before_script:
    - wget --verbose https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
    - tar -xf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
    - chmod +x ./hugo

script:
    - mkdir -p public
    - ./hugo -s hypathianet -d ../public
    - ls -l ./public

deploy:
  provider: pages
  skip-cleanup: true
  repo: hypathianet/hypathia.github.io
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  local-dir: public
  fqdn: hypthia.net
  on:
    branch: master
